# Edit this file to tune raw range mapping.
# For each joint:
# - range_min maps to joint lower limit
# - range_max maps to joint upper limit

shoulder_pan:
  id: 1
  range_min: 847
  range_max: 3371
shoulder_lift:
  id: 2
  range_min: 870
  range_max: 3270
elbow_flex:
  id: 3
  range_min: 856
  range_max: 3081
wrist_flex:
  id: 4
  range_min: 893
  range_max: 3228
wrist_roll:
  id: 5
  range_min: 52
  range_max: 3911
gripper:
  id: 6
  range_min: 2037
  range_max: 3519
